# -*- mode: ruby -*-
# vi: set ft=ruby :

 Vagrant.require_version ">= 1.8"

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/23-cloud-base"
  config.vm.box_check_update = true 

  config.vm.synced_folder "..", "/hellweg2d"

   config.vm.provider "virtualbox" do |vb|
     vb.linked_clone = true
     vb.memory = "512"
     vb.cpus = 4
   end

  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y clang gcc-c++ cmake make boost-devel tmux htop git python-devel libffi-devel redhat-rpm-config python3-devel
  SHELL
end
